# Generated by Django 5.2.5 on 2025-08-15 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_plan_userplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FavoriteMovie_movie_FK', to='app.movie')),
                ('user_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FavoriteMovie_user_FK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
